'''
toolbox.py

A package containing generally useful functions, organzied into submodules which may be loaded
directly form toolbox along with the most commonly used functions.

Based on a series of modules that were packaged up in Jan. 2020, scripts written prior to that
should be (mostly) backwards comparable if they contain the wild import "from toolbox import *"

Last updated January 2020
by Trevor Arp
'''

'''
Utilities module contains commonly used general purpose functions.
'''
import toolbox.utils as utils
from toolbox.utils import find_run
from toolbox.utils import find_savefile

'''
Functions for manipulating scans, a few common functions are directly imported
'''
import toolbox.scans as scans
from toolbox.scans import slowscan_2_line
from toolbox.scans import range_from_log


'''
Contains functions relating to displaying data runs, a few common functions are directly imported
'''
import toolbox.display as display
from toolbox.display import figure_format
from toolbox.display import paper_figure_format
#from toolbox.display import set_img_ticks
#from toolbox.display import scale_bar_plot
#from toolbox.display import format_plot_axes
#from toolbox.display import get_viridis
#from toolbox.display import get_figure

'''
Contains functions relating to specific visualizations
'''
import toolbox.visual as visual

'''
Calibration functions
'''
import toolbox.calibration as calibration

'''
Fitting functions
'''
import toolbox.fitting as fitting

'''
Simulation functions
'''
import toolbox.sim as sim

'''
Functions for processing runs generated by various instruction sets
'''
import toolbox.process as process
from toolbox.process import load_run
from toolbox.process import get_processed_data
from toolbox.process import ProcessRun
from toolbox.process import dataimg

'''
Functions for processing runs generated by various instruction sets
'''
import toolbox.postprocess as postprocess
