'''
trevorarp.py

Trevor Arp's personal code toolbox

A package containing generally useful functions, organzied into submodules which may be loaded
directly form toolbox along with the most commonly used functions.

Based on a series of modules that were packaged up in Jan. 2020, scripts written prior to that
should be (mostly) backwards comparable if they contain the wild import "from toolbox import *"

Last updated February 2020
by Trevor Arp
'''

'''
Utilities module contains commonly used general purpose functions.
'''
import trevorarp.utils as utils

'''
Contains functions relating to displaying data runs, a few common functions are directly imported
'''
import trevorarp.display as display

'''
Fitting functions
'''
import trevorarp.fitting as fitting

'''
Simulation functions
'''
import trevorarp.sim as sim

'''
Mathematical functions
'''
import trevorarp.math as math

'''
Physics functions
'''
import trevorarp.physics as physics

'''
Functions for processing runs generated by various instruction sets
'''
import trevorarp.processing as processing

import trevorarp.data as data

import trevorarp.nanosquid as nanosquid

# '''
# Code for processing things from older versions of the DAQ
# '''
# import trevorarp.legacy as legacy
