'''
trevorarp.py

Trevor Arp's personal code toolbox

A package containing generally useful functions, organzied into submodules which may be loaded
directly form toolbox along with the most commonly used functions.

Based on a series of modules that were packaged up in Jan. 2020, scripts written prior to that
should be (mostly) backwards comparable if they contain the wild import "from toolbox import *"

Last updated February 2020
by Trevor Arp
'''

'''
Utilities module contains commonly used general purpose functions.
'''
import trevorarp.utils as utils

'''
Functions for manipulating scans, a few common functions are directly imported
'''
import trevorarp.scans as scans
from trevorarp.scans import slowscan_2_line
from trevorarp.scans import range_from_log


'''
Contains functions relating to displaying data runs, a few common functions are directly imported
'''
import trevorarp.display as display

'''
Contains functions relating to specific visualizations
'''
import trevorarp.visual as visual

'''
Fitting functions
'''
import trevorarp.fitting as fitting

'''
Simulation functions
'''
import trevorarp.sim as sim

'''
Functions for processing runs generated by various instruction sets
'''
import trevorarp.postprocess as postprocess

'''
Code for processing things from older versions of the DAQ
'''
import trevorarp.legacy as legacy
