'''
trevorarp.py

Trevor Arp's personal code toolbox

A package containing generally useful functions, organzied into submodules which may be loaded
directly form toolbox along with the most commonly used functions.

Based on a series of modules that were packaged up in Jan. 2020, scripts written prior to that
should be (mostly) backwards comparable if they contain the wild import "from toolbox import *"

Last updated February 2020
by Trevor Arp
'''

'''
Utilities module contains commonly used general purpose functions.
'''
import toolbox.utils as utils

'''
Functions for manipulating scans, a few common functions are directly imported
'''
import toolbox.scans as scans
from toolbox.scans import slowscan_2_line
from toolbox.scans import range_from_log


'''
Contains functions relating to displaying data runs, a few common functions are directly imported
'''
import toolbox.display as display
from toolbox.display import figure_format
from toolbox.display import paper_figure_format

'''
Contains functions relating to specific visualizations
'''
import toolbox.visual as visual

'''
Fitting functions
'''
import toolbox.fitting as fitting

'''
Simulation functions
'''
import toolbox.sim as sim

'''
Functions for processing runs generated by various instruction sets
'''
import toolbox.postprocess as postprocess
